require "./deploy_destination"
require "./deploy_config"

module VoIPAppz
  # Generates the Kamal DESTINATION override for a customer application
  # (the `voipappz/app` template) from a `DeployDestination` the CLI already
  # knows about.
  #
  # Why generate it at all: those files are hand-tuned per host today, and each
  # one encodes a production incident in a comment — `proxy: false` because
  # "Kong owns 80/443", a fixed `:8888` publish, an ssh user, an env-file path.
  # Every one of those facts is already in config/deploy.<dest>.yml, so writing
  # them twice is how they drift.
  #
  # This produces an OVERRIDE, not a whole config: Kamal layers
  # `config/deploy.<dest>.yml` on top of the app's base `config/deploy.yml`, so
  # only host-specific keys belong here. Keep it that way — a full config would
  # duplicate (and then contradict) the app's own base file.
  module AppDeploy
    extend self

    # The app's production image listens here (Dockerfile.production EXPOSEs
    # 3000 and Kamal's base config sets app_port: 3000).
    APP_PORT = 3000

    # Loopback-published port used when the node's own proxy owns 80/443.
    # 127.0.0.1 on purpose: the app is reachable only through that proxy.
    DEFAULT_PUBLISH_PORT = 8888

    # Where the runtime env-file lives on the target.
    #
    # Deploying as root means a system path; an unprivileged deploy user cannot
    # write /etc, so their home is the only place they can place it without
    # sudo. Matches the two real destinations: /etc/voipappz/secrets.env (root)
    # and /home/itdroot/voipappz-app.env (itdroot).
    def env_file_path(user : String) : String
      user == "root" ? "/etc/voipappz/secrets.env" : "/home/#{user}/voipappz-app.env"
    end

    # The one variable a tenant fork must set (README: "A tenant fork changes
    # env, not code"). Baked into the bundle at build time, so it is a builder
    # arg rather than a runtime env var.
    def mothership_url(config : VoIPAppz::DeployConfig?) : String
      domain = config.try(&.organization.domain) || ""
      return "" if domain.empty? || domain == "voipappz.local"
      domain.starts_with?("http") ? domain : "https://#{domain}"
    end

    # Render the destination override.
    #
    # kong: the node already runs a proxy on 80/443 (every VoIPAppz app node
    # does), so Kamal must NOT start kamal-proxy — it would fight for the port.
    # The container is published on loopback instead and the node's proxy
    # fronts it. Set false only for a bare host with nothing on 80/443.
    def destination_yaml(
      dest : VoIPAppz::DeployDestination,
      mothership : String = "",
      kong : Bool = true,
      publish_port : Int32 = DEFAULT_PUBLISH_PORT,
    ) : String
      env_file = env_file_path(dest.user)

      String.build do |io|
        io << "# Kamal DESTINATION override — GENERATED by `voipappz app deploy`.\n"
        io << "# Regenerated on every deploy; edit config/deploy.<dest>.yml in the\n"
        io << "# CLI project instead, which is the source of truth for this host.\n"
        io << "#\n"
        if kong
          io << "# This host runs the VoIPAppz stack, whose Kong owns 80/443. kamal-proxy\n"
          io << "# is therefore DISABLED (proxy: false) and the container is published on\n"
          io << "# 127.0.0.1:#{publish_port} only — the node's own proxy fronts it. Starting\n"
          io << "# kamal-proxy here would contend for 80/443 with Kong.\n"
        else
          io << "# Bare host: nothing else owns 80/443, so kamal-proxy fronts the app and\n"
          io << "# health-checks it on #{APP_PORT}.\n"
        end
        io << "\n"

        io << "servers:\n"
        io << "  web:\n"
        io << "    hosts:\n"
        io << "      - #{dest.host}\n"
        if kong
          io << "    proxy: false\n"
        end
        io << "    options:\n"
        io << "      env-file: #{env_file}\n"
        if kong
          io << "      publish:\n"
          io << "        - \"127.0.0.1:#{publish_port}:#{APP_PORT}\"\n"
        end
        io << "\n"

        unless kong
          io << "proxy:\n"
          io << "  ssl: false\n"
          io << "  hosts:\n"
          io << "    - #{dest.host}\n"
          io << "  app_port: #{APP_PORT}\n"
          io << "  healthcheck:\n"
          io << "    path: /health\n"
          io << "    interval: 3\n"
          io << "    timeout: 5\n"
          io << "\n"
        end

        io << "ssh:\n"
        io << "  user: #{dest.user}\n"
        io << "  port: #{dest.ssh_port}\n"
        io << "  keys:\n"
        io << "    - \"#{dest.key}\"\n"

        unless mothership.empty?
          io << "\n"
          io << "builder:\n"
          io << "  arch: amd64\n"
          io << "  args:\n"
          io << "    VITE_MOTHERSHIP_URL: #{mothership}\n"
        end
      end
    end

    # `kamal app stop` must run BEFORE deploy when the container is published on
    # a FIXED host port: Kamal starts the new container before removing the old
    # one, and the second bind fails with
    #   docker: Bind for 0.0.0.0:8888 failed: port is already allocated (exit 125)
    # kamal-proxy deploys do not need this — they never publish a host port.
    def stop_first?(kong : Bool) : Bool
      kong
    end

    # Kamal's post-deploy hook probes KAMAL_HEALTHCHECK_URL from the machine
    # running the deploy. When the app is published on loopback behind Kong,
    # that port is not reachable from here, so every probe returns 000 and
    # fails an otherwise-successful deploy. Leave it unset in that case and let
    # the hook skip itself.
    def healthcheck_url(kong : Bool, domain : String) : String
      return "" if kong || domain.empty?
      domain.starts_with?("http") ? domain : "https://#{domain}"
    end
  end
end
