require "http/client"
require "json"
require "./colors"
require "./env_file"
require "./project"

module VoIPAppz
  # An MCP CLIENT, over HTTP.
  #
  # The CLI has been an MCP *server* (commands/mcp.cr, stdio) since it gained
  # the surface. This is the other direction: the platform runs MCP servers of
  # its own and the CLI could not read any of them.
  #
  #   voipappz-api    POST /tasks/mcp   resources only, public, read-only
  #   portal deno-api POST /mcp         DuckDB tools, bearer-gated
  #
  # Hand-rolled rather than through the mcp shard: its client ships a STDIO
  # transport only (lib/mcp/src/mcp/client/stdio_client_transport.cr), and both
  # servers here speak the streamable-HTTP request half — a single POST of
  # JSON-RPC 2.0, answered with JSON. No SSE, no session handshake. That is
  # four methods, so the shard would be a dependency for less code than this.
  module McpClient
    extend self

    PROTOCOL_VERSION = "2025-06-18"

    class Error < Exception; end

    # A named server, or a URL. The names exist because typing the API's path
    # from memory is how you conclude it has no MCP at all: /mcp, /api/mcp and
    # /v1/mcp all answer 404, and the route is /tasks/mcp.
    record Server, name : String, url : String, token : String?

    # Resolve, or explain and stop. Every command wants this; none should carry
    # its own copy of the rescue.
    def resolve!(target : String) : Server
      resolve(target)
    rescue ex : Error
      STDERR.puts Colors.red(ex.message.to_s)
      exit 1
    end

    def resolve(target : String) : Server
      case target
      when "api", ""
        port = ENV["VA_API_PORT"]?.presence || "5000"
        Server.new("voipappz-api", "http://127.0.0.1:#{port}/tasks/mcp", nil)
      when "portal"
        Server.new("portal", ENV["VA_PORTAL_MCP_URL"]?.presence || "http://localhost:4001/mcp", portal_token)
      else
        unless target.starts_with?("http://") || target.starts_with?("https://")
          raise Error.new("unknown server '#{target}' — use `api`, `portal`, or a URL")
        end
        Server.new(target, target, nil)
      end
    end

    # The portal's token is generated by its scripts/dev-mcp-token.sh into a
    # git-ignored .mcp.env beside the app. Loopback does not need it when the
    # server allows that, so a missing file is not an error here — the server
    # says whether it minded.
    def portal_token : String?
      return ENV["MCP_AUTH_TOKEN"]?.presence if ENV["MCP_AUTH_TOKEN"]?.presence
      sibling = File.join(File.dirname(VoIPAppz::Project.root), "app", ".mcp.env")
      VoIPAppz::EnvFile.load(sibling)["MCP_AUTH_TOKEN"]?.presence
    end

    # One JSON-RPC round trip. Raises on transport failure and on a JSON-RPC
    # error object — a `result` is the only thing that comes back.
    def call(server : Server, method : String, params = nil) : JSON::Any
      body = {jsonrpc: "2.0", id: 1, method: method, params: params}.to_json
      headers = HTTP::Headers{"Content-Type" => "application/json"}
      headers["Authorization"] = "Bearer #{server.token}" if server.token

      response =
        begin
          HTTP::Client.post(server.url, headers: headers, body: body)
        rescue ex
          raise Error.new("#{server.url} is not answering (#{ex.message})")
        end

      # A 404 here is nearly always the wrong path rather than a missing
      # server, so say which URL was tried.
      raise Error.new("#{server.url} answered #{response.status_code}") unless response.success?

      doc = begin
        JSON.parse(response.body)
      rescue JSON::ParseException
        raise Error.new("#{server.url} answered #{response.status_code} with something that is not JSON")
      end

      if error = doc["error"]?
        code = error["code"]?.try(&.as_i?) || 0
        raise Error.new("#{method} refused (#{code}): #{error["message"]?.try(&.as_s?) || error.to_json}")
      end
      doc["result"]? || JSON::Any.new({} of String => JSON::Any)
    end

    # `initialize` is what identifies the server, and a client that skips it is
    # relying on servers being lenient about the order.
    def handshake(server : Server) : JSON::Any
      call(server, "initialize", {
        protocolVersion: PROTOCOL_VERSION,
        capabilities:    {} of String => String,
        clientInfo:      {name: "voipappz-cli", version: "0.1.0"},
      })
    end

    def tools(server : Server) : Array(JSON::Any)
      call(server, "tools/list")["tools"]?.try(&.as_a?) || [] of JSON::Any
    end

    def resources(server : Server) : Array(JSON::Any)
      call(server, "resources/list")["resources"]?.try(&.as_a?) || [] of JSON::Any
    end

    def read(server : Server, uri : String) : Array(JSON::Any)
      call(server, "resources/read", {uri: uri})["contents"]?.try(&.as_a?) || [] of JSON::Any
    end

    def call_tool(server : Server, name : String, arguments : JSON::Any?) : JSON::Any
      call(server, "tools/call", {name: name, arguments: arguments || JSON.parse("{}")})
    end
  end
end
