require "./project"
require "random/secure"
require "./colors"

module VoIPAppz::SecretsHelper
  # The project, resolved — not wherever the binary was invoked from. On a node
  # the binary is in /opt/cli/bin and the project in /opt/va, so `Dir.current`
  # pointed secrets, .env and config/ at a directory that has none of them.
  def self.project_dir : String
    VoIPAppz::Project.root
  end

  # Secrets generated by setup — each is written to secrets/<name>.txt (some are
  # bind-mounted as docker secrets, e.g. nats_token) AND consumed via .env.
  # nats_token: hex so it's URL-safe inside nats://default:<token>@host.
  SECRETS = {
    "postgres_password"      => {length: 24, method: :hex},
    "freeswitch_password"    => {length: 24, method: :base64},
    "nats_token"             => {length: 32, method: :hex},
    "secret_key"             => {length: 64, method: :hex},
    "vault_master_key"       => {length: 32, method: :hex},
    "s3_key"                 => {length: 24, method: :hex},
    "s3_secret"              => {length: 32, method: :hex},
    "license_encryption_key" => {length: 32, method: :hex},
    "license_jwt"            => {length: 32, method: :hex},
  }

  # Generate all secrets as an in-memory hash.
  # Resolution order per secret:
  #   1. secrets/<name>.txt on disk (persists across .env regen + volume restores)
  #   2. .env (back-compat — operators who set values manually)
  #   3. freshly generated via `openssl rand`
  # Persisted to secrets/<name>.txt so subsequent runs are idempotent. The
  # postgres data volume's password lives there, so re-running setup never
  # silently mismatches what's baked into the database.
  def self.generate_all_hash(force : Bool = false) : Hash(String, String)
    persisted = force ? {} of String => String : read_persisted_secrets
    env_secrets = force ? {} of String => String : read_env_secrets

    secrets = {} of String => String
    SECRETS.each do |name, opts|
      if !force && persisted.has_key?(name) && !persisted[name].empty?
        secrets[name] = persisted[name]
      elsif !force && env_secrets.has_key?(name) && !env_secrets[name].empty?
        secrets[name] = env_secrets[name]
      else
        secrets[name] = generate_secret(opts[:length], opts[:method])
      end
    end

    write_persisted_secrets(secrets)
    secrets
  end

  # Read whichever <name>.txt files exist under secrets/. Missing files
  # are treated as "not set" — the caller falls back to .env or generation.
  def self.read_persisted_secrets : Hash(String, String)
    result = {} of String => String
    secrets_dir = File.join(project_dir, "secrets")
    return result unless Dir.exists?(secrets_dir)

    SECRETS.each_key do |name|
      path = File.join(secrets_dir, "#{name}.txt")
      next unless File.exists?(path)
      value = File.read(path).strip
      result[name] = value unless value.empty?
    end
    result
  end

  # Write each secret to secrets/<name>.txt. The directory is 0700 so only
  # the deploy user can list it; the files themselves are 0444 so docker
  # compose secrets (which preserve host perms when bind-mounting) can be
  # read by non-root container users (the curl image runs as uid 100, and
  # 1000, etc.). Idempotent — safe to call repeatedly.
  def self.write_persisted_secrets(secrets : Hash(String, String)) : Nil
    secrets_dir = File.join(project_dir, "secrets")
    Dir.mkdir_p(secrets_dir)
    File.chmod(secrets_dir, 0o700) rescue nil
    secrets.each do |name, value|
      next unless SECRETS.has_key?(name)
      next if value.empty?
      path = File.join(secrets_dir, "#{name}.txt")
      if File.exists?(path) && File.read(path).strip == value
        next
      end
      # Files are written 0444 so non-root containers can read them via
      # docker secrets bind-mounts. That makes File.write fail on re-runs,
      # so chmod 0600 first to allow overwrite, then re-lock to 0444.
      File.chmod(path, 0o600) rescue nil if File.exists?(path)
      File.write(path, value)
      File.chmod(path, 0o444) rescue nil
    end
  end

  # Read existing secrets from .env file
  def self.read_env_secrets : Hash(String, String)
    result = {} of String => String
    env_path = File.join(project_dir, ".env")
    return result unless File.exists?(env_path)

    # Map .env keys back to secret names
    key_map = {
      "VA_FREESWITCH_PASSWORD"    => "freeswitch_password",
      "VA_S3_KEY"                 => "s3_key",
      "VA_S3_SECRET"              => "s3_secret",
      "VA_LICENSE_ENCRYPTION_KEY" => "license_encryption_key",
      "VA_LICENSE_JWT_SECRET"     => "license_jwt",
    }

    File.each_line(env_path) do |line|
      line = line.strip
      next if line.empty? || line.starts_with?("#")
      if line.includes?("=")
        key, value = line.split("=", 2)
        secret_name = key_map[key.strip]?
        result[secret_name] = value.strip if secret_name
      end
    end
    result
  end

  # Validate that all required secrets exist in .env
  def self.validate_env : {Bool, Array(String)}
    secrets = read_env_secrets
    missing = [] of String
    SECRETS.each_key do |name|
      unless secrets.has_key?(name) && !secrets[name].empty?
        missing << name
      end
    end
    {missing.empty?, missing}
  end

  # Show hashed secrets from .env
  def self.show_hashed : Array({String, String})
    secrets = read_env_secrets

    SECRETS.keys.map do |name|
      value = secrets[name]?
      if value && !value.empty?
        hash = value.bytes.reduce(0_u64) { |acc, b| acc &* 31 &+ b }.to_s(16)[0, 16]
        {name, hash + "..."}
      else
        {name, "MISSING"}
      end
    end
  end

  # Alphanumeric only: these values land in .env, connection strings and URLs
  # (VA_DATABASE_URL, VA_REDIS_URL, …), where +, / and = from raw base64 have
  # to be percent-encoded or they corrupt the URL. The old implementation
  # generated base64 and stripped those characters back out.
  SECRET_ALPHABET = ('a'..'z').to_a + ('A'..'Z').to_a + ('0'..'9').to_a

  # Draws from the OS CSPRNG (getrandom/urandom) instead of shelling out to
  # `openssl rand`. That removes a hard runtime dependency the local installer
  # never guaranteed — and, worse, a silent-failure mode: a non-zero openssl
  # exit left stdout empty, so this returned an EMPTY STRING and setup happily
  # wrote a blank postgres/vault password into .env.
  def self.generate_secret(length : Int32, method : Symbol) : String
    case method
    when :hex
      # Matches `openssl rand -hex <length>`: length bytes -> 2*length chars.
      Random::Secure.hex(length)
    else
      String.build(length) do |io|
        length.times { io << SECRET_ALPHABET[Random::Secure.rand(SECRET_ALPHABET.size)] }
      end
    end
  end
end
